// 학교 데이터베이스
export const schoolDatabase = [
  { name: "서울대학교", domain: "snu.ac.kr", aliases: ["서울대"] },
  { name: "연세대학교", domain: "yonsei.ac.kr", aliases: ["연세대", "연대"] },
  { name: "고려대학교", domain: "korea.ac.kr", aliases: ["고려대", "고대"] },
  { name: "성균관대학교", domain: "skku.edu", aliases: ["성균관대", "성대"] },
  { name: "서강대학교", domain: "sogang.ac.kr", aliases: ["서강대"] },
  { name: "한양대학교", domain: "hanyang.ac.kr", aliases: ["한양대"] },
  { name: "중앙대학교", domain: "cau.ac.kr", aliases: ["중앙대", "중대"] },
  { name: "경희대학교", domain: "khu.ac.kr", aliases: ["경희대"] },
  { name: "한국외국어대학교", domain: "hufs.ac.kr", aliases: ["한국외대", "외대"] },
  { name: "서울시립대학교", domain: "uos.ac.kr", aliases: ["시립대"] },
  { name: "이화여자대학교", domain: "ewha.ac.kr", aliases: ["이화여대", "이대"] },
  { name: "건국대학교", domain: "konkuk.ac.kr", aliases: ["건국대", "건대"] },
  { name: "동국대학교", domain: "dongguk.edu", aliases: ["동국대"] },
  { name: "홍익대학교", domain: "hongik.ac.kr", aliases: ["홍익대", "홍대"] },
  { name: "국민대학교", domain: "kookmin.ac.kr", aliases: ["국민대"] },
  { name: "숭실대학교", domain: "ssu.ac.kr", aliases: ["숭실대"] },
  { name: "세종대학교", domain: "sejong.ac.kr", aliases: ["세종대"] },
  { name: "가천대학교", domain: "gachon.ac.kr", aliases: ["가천대"] },
  { name: "아주대학교", domain: "ajou.ac.kr", aliases: ["아주대"] },
  { name: "인하대학교", domain: "inha.ac.kr", aliases: ["인하대"] },
  { name: "KAIST", domain: "kaist.ac.kr", aliases: ["카이스트"] },
  { name: "POSTECH", domain: "postech.ac.kr", aliases: ["포스텍"] },
  { name: "GIST", domain: "gist.ac.kr", aliases: ["지스트"] },
  { name: "UNIST", domain: "unist.ac.kr", aliases: ["유니스트"] },
  { name: "국립군산대학교", domain: "kunsan.ac.kr", aliases: ["군산대", "국립군산대"] },
  { name: "전북대학교", domain: "jbnu.ac.kr", aliases: ["전북대"] },
  { name: "전남대학교", domain: "jnu.ac.kr", aliases: ["전남대"] },
  { name: "충남대학교", domain: "cnu.ac.kr", aliases: ["충남대"] },
  { name: "경북대학교", domain: "knu.ac.kr", aliases: ["경북대"] },
  { name: "부산대학교", domain: "pusan.ac.kr", aliases: ["부산대"] },
  { name: "강원대학교", domain: "kangwon.ac.kr", aliases: ["강원대"] },
  { name: "제주대학교", domain: "jejunu.ac.kr", aliases: ["제주대"] },
];
